[project]
name = "pdfExtractor"
version = "0.1.0"
description = "PDF extraction wrapper built on PyMuPDF"
readme = "README.md"
license = {file = "LICENSE"}
requires-python = ">=3.10"
dependencies = [
    "pymupdf>=1.27.2.2"
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]